### TEST GET / 
GET http://localhost:5004

## TEST POST /API/AUTH/SIGNUP
POST http://localhost:5001/api/auth/signup HTTP/1.1
content-type: application/json

{
  "username":"johnnyseed",
  "email": "john21@gmail.com",
  "password": "johnseed22"
}